import * as fs from "fs";
import * as path from "path";
import Ajv from "ajv-draft-04";
import standaloneCode from "ajv/dist/standalone/index.js";
import { _ } from "ajv/dist/compile/codegen/index.js";
import { toMethodName, toClassName } from "./naming";

// Minimal shape of the JSON-schema nodes we traverse. The schemas are untyped JSON; this captures
// just the fields the generator reads so the pipeline below is typed end-to-end.
interface SchemaNode {
  type?: string | string[];
  enum?: string[];
  $ref?: string;
  anyOf?: SchemaNode[];
  items?: SchemaNode;
  properties?: Record<string, SchemaNode>;
  required?: string[];
  description?: string;
  version?: string;
  definitions?: Record<string, SchemaNode>;
}

interface PropInfo {
  name: string;
  isReq: boolean;
  tsType: string;
  desc: string;
  node: SchemaNode;
}

interface ObjectDef {
  defName: string | null;
  className: string;
  desc: string;
  properties: PropInfo[];
  requiredList: string[];
}

const AJV_UNICODE_LENGTH_RUNTIME = 'require("ajv/dist/runtime/ucs2length").default';
const AJV_DEEP_EQUAL_RUNTIME = 'require("ajv/dist/runtime/equal").default';

const STANDALONE_VALIDATOR_HELPERS = `// @ts-nocheck
// Generated by scripts/generate-clockify-manifest.ts. Do not edit by hand.

function clockifyUnicodeLength(value: string): number {
  const length = value.length;
  let codePointLength = 0;
  let position = 0;
  let codeUnit: number;
  while (position < length) {
    codePointLength += 1;
    codeUnit = value.charCodeAt(position++);
    if (codeUnit >= 0xd800 && codeUnit <= 0xdbff && position < length) {
      codeUnit = value.charCodeAt(position);
      if ((codeUnit & 0xfc00) === 0xdc00) position += 1;
    }
  }
  return codePointLength;
}

function clockifyJsonDeepEqual(left: any, right: any): boolean {
  if (left === right) return true;
  if (left && right && typeof left === "object" && typeof right === "object") {
    if (left.constructor !== right.constructor) return false;

    let length: number;
    let index: number;
    let keys: string[];
    if (Array.isArray(left)) {
      length = left.length;
      if (length !== right.length) return false;
      for (index = length; index-- !== 0; ) {
        if (!clockifyJsonDeepEqual(left[index], right[index])) return false;
      }
      return true;
    }

    if (left.constructor === RegExp) {
      return left.source === right.source && left.flags === right.flags;
    }
    if (left.valueOf !== Object.prototype.valueOf) return left.valueOf() === right.valueOf();
    if (left.toString !== Object.prototype.toString) return left.toString() === right.toString();

    keys = Object.keys(left);
    length = keys.length;
    if (length !== Object.keys(right).length) return false;
    for (index = length; index-- !== 0; ) {
      if (!Object.prototype.hasOwnProperty.call(right, keys[index])) return false;
    }
    for (index = length; index-- !== 0; ) {
      const key = keys[index];
      if (!clockifyJsonDeepEqual(left[key], right[key])) return false;
    }
    return true;
  }
  return left !== left && right !== right;
}

function clockifyUriFormat(value: string): boolean {
  try {
    new URL(value);
    return true;
  } catch {
    return false;
  }
}

const clockifyStandaloneFormats = {
  uri: { type: "string", validate: clockifyUriFormat },
} as const;
`;

function replaceExactlyOnce(
  source: string,
  target: string,
  replacement: string,
  description: string,
): string {
  const occurrences = source.split(target).length - 1;
  if (occurrences !== 1) {
    throw new Error(`Expected exactly one ${description}; found ${occurrences}.`);
  }
  return source.replace(target, replacement);
}

function generateManifestValidators(
  schemasDir: string,
  outDir: string,
  schemaNames: readonly string[],
): void {
  const ajv = new Ajv({
    allErrors: true,
    strict: false,
    code: {
      esm: true,
      formats: _`clockifyStandaloneFormats`,
      lines: true,
      source: true,
    },
  });
  ajv.addFormat("uri", {
    type: "string",
    validate(value: string) {
      try {
        new URL(value);
        return true;
      } catch {
        return false;
      }
    },
  });

  const validatorExports: Record<string, string> = {};
  for (const schemaName of schemaNames) {
    const version = schemaName.replace(".json", "");
    const schemaKey = `clockify-manifest-${version}`;
    const schema = JSON.parse(fs.readFileSync(path.join(schemasDir, schemaName), "utf8"));
    ajv.addSchema(schema, schemaKey);
    validatorExports[`validateManifest${version.replace(".", "_")}`] = schemaKey;
  }

  let generated = standaloneCode(ajv, validatorExports);
  generated = replaceExactlyOnce(
    generated,
    AJV_UNICODE_LENGTH_RUNTIME,
    "clockifyUnicodeLength",
    "AJV Unicode-length helper import",
  );
  generated = replaceExactlyOnce(
    generated,
    AJV_DEEP_EQUAL_RUNTIME,
    "clockifyJsonDeepEqual",
    "AJV deep-equality helper import",
  );
  const formatReferences = generated.split("clockifyStandaloneFormats").length - 1;
  if (formatReferences !== 1) {
    throw new Error(
      `Expected exactly one standalone URI-format reference; found ${formatReferences}.`,
    );
  }
  const unsupportedRuntimeImport = generated.match(/\brequire\s*\([^)]*\)/u)?.[0];
  if (unsupportedRuntimeImport) {
    throw new Error(`Unsupported AJV standalone runtime import: ${unsupportedRuntimeImport}`);
  }
  if (/\beval\s*\(|\bnew\s+Function\b/u.test(generated)) {
    throw new Error("AJV standalone output contains runtime string code generation.");
  }

  const outPath = path.join(outDir, "manifest-validators.ts");
  fs.writeFileSync(outPath, `${STANDALONE_VALIDATOR_HELPERS}\n${generated.trimEnd()}\n`, "utf8");
  console.log(`Generated static manifest validators at ${outPath}`);
}

const DEFINITIONS_MAP: Record<string, string> = {
  lifecycle: "lifecycleEvent",
};

function getDefinitionSimpleClassName(defName: string): string {
  const suffix = DEFINITIONS_MAP[defName] || defName;
  return toClassName("Clockify_" + suffix);
}

function getEnumSetterMethodName(
  definition: string | null,
  property: string,
  value: string,
): string {
  let val = value;
  if (definition === "component") {
    if (property === "accessLevel") {
      val = "allow_" + val;
    }
  } else if (definition === "lifecycle") {
    if (property === "type") {
      val = "on_" + val;
    }
  } else if (definition === "webhook") {
    if (property === "event") {
      val = "on_" + val;
    }
  } else if (definition === "setting") {
    if (property === "type") {
      val = "as_" + val;
    } else if (property === "accessLevel") {
      val = "allow_" + val;
    }
  } else if (definition === null) {
    if (property === "minimalSubscriptionPlan") {
      val = "require_" + val + "_plan";
    }
  }
  return toMethodName(val);
}

function resolveRef(ref: string): string {
  return ref.substring(ref.lastIndexOf("/") + 1);
}

// Enum values for a property node, resolving a `$ref` to its definition first. Returns [] when the
// node (or the definition it references) has no enum.
function getEnumValues(node: SchemaNode, definitions: Record<string, SchemaNode>): string[] {
  const resolved = node.$ref ? definitions[resolveRef(node.$ref)] : node;
  return resolved && resolved.enum ? resolved.enum : [];
}

function getTSType(node: SchemaNode, definitions: Record<string, SchemaNode>): string {
  if (node.anyOf) {
    return node.anyOf.map((n) => getTSType(n, definitions)).join(" | ");
  }
  if (node.$ref) {
    const ref = resolveRef(node.$ref);
    if (ref === "url" || ref === "selfHostedSettings") {
      return "string";
    }
    return getDefinitionSimpleClassName(ref);
  }
  const type = node.type;
  if (Array.isArray(type)) {
    return type
      .map((t) => {
        if (t === "integer") return "number";
        if (t === "array") return "any[]";
        if (t === "object") return "Record<string, any>";
        return t;
      })
      .join(" | ");
  }
  if (type === "integer") {
    return "number";
  }
  if (type === "boolean") {
    return "boolean";
  }
  if (type === "string") {
    if (node.enum) {
      return node.enum.map((e) => JSON.stringify(e)).join(" | ");
    }
    return "string";
  }
  if (type === "array") {
    if (node.items) {
      return `${getTSType(node.items, definitions)}[]`;
    }
    // Items-less arrays default to string[], matching the Java processor's List<String>.
    return "string[]";
  }
  if (type === "object") {
    return "Record<string, any>";
  }
  return "any";
}

function jsDoc(desc: string, indent = ""): string {
  const cleaned = desc.replace(/\*\//g, "* /").replace(/\s+/g, " ").trim();
  if (!cleaned) return "";
  return `${indent}/** ${cleaned} */\n`;
}

function getPropertiesInfo(
  propertiesNode: Record<string, SchemaNode>,
  requiredList: string[],
  definitions: Record<string, SchemaNode>,
): PropInfo[] {
  const required = new Set(requiredList);
  const props: PropInfo[] = [];
  for (const [propName, propNode] of Object.entries(propertiesNode)) {
    if (propName === "schemaVersion") continue;
    props.push({
      name: propName,
      isReq: required.has(propName),
      tsType: getTSType(propNode, definitions),
      desc: propNode.description || "",
      node: propNode,
    });
  }
  return props;
}

// The manifest plus every `object` definition, each carrying its resolved properties and required
// list. The manifest is appended last with `defName: null` (it has no definition name).
function collectObjectDefs(
  schema: SchemaNode,
  definitions: Record<string, SchemaNode>,
): ObjectDef[] {
  const objectDefs: ObjectDef[] = [];
  for (const [defName, defNode] of Object.entries(definitions)) {
    if (defNode.type === "object") {
      objectDefs.push({
        defName,
        className: getDefinitionSimpleClassName(defName),
        desc: defNode.description ?? "",
        properties: getPropertiesInfo(
          defNode.properties ?? {},
          defNode.required ?? [],
          definitions,
        ),
        requiredList: defNode.required ?? [],
      });
    }
  }
  objectDefs.push({
    defName: null,
    className: "ClockifyManifest",
    desc: schema.description ?? "",
    properties: getPropertiesInfo(schema.properties ?? {}, schema.required ?? [], definitions),
    requiredList: schema.required ?? [],
  });
  return objectDefs;
}

// Required builder steps follow the schema's `required` array order to match the Java annotation
// processor (DefinitionProcessor reads `required`, not declaration order). Optionals keep
// declaration order and collapse into a single trailing step.
function splitProps(obj: ObjectDef): { requiredProps: PropInfo[]; optionalProps: PropInfo[] } {
  const requiredProps = obj.requiredList
    .map((name) => obj.properties.find((p) => p.name === name))
    .filter((p): p is PropInfo => p != null && p.isReq);
  const optionalProps = obj.properties.filter((p) => !p.isReq);
  return { requiredProps, optionalProps };
}

function firstStepName(
  obj: ObjectDef,
  requiredProps: PropInfo[],
  optionalProps: PropInfo[],
): string {
  if (requiredProps.length > 0) return `${obj.className}Builder_${requiredProps[0].name}`;
  return optionalProps.length > 0
    ? `${obj.className}Builder_Optional`
    : `${obj.className}Builder_Build`;
}

// Top-level enum constants (scope, minimalSubscriptionPlan, ...) as `as const` objects.
function emitEnums(definitions: Record<string, SchemaNode>): string {
  let out = "";
  for (const [defName, defNode] of Object.entries(definitions)) {
    if (defNode.type === "string" && defNode.enum) {
      const className = getDefinitionSimpleClassName(defName);
      out += `export const ${className} = {\n`;
      for (const val of defNode.enum) {
        // Quote keys so enum values that aren't valid JS identifiers still emit valid TypeScript.
        out += `  "${val}": "${val}",\n`;
      }
      out += `} as const;\n\n`;
      out += `export type ${className} = typeof ${className}[keyof typeof ${className}];\n\n`;
    }
  }
  return out;
}

// The readonly data interface for one model (manifest or definition).
function emitInterface(obj: ObjectDef, version: string): string {
  const isManifest = obj.defName === null;
  const isResource =
    obj.defName !== null && ["lifecycle", "webhook", "component"].includes(obj.defName);
  const heritage = isResource ? " extends ClockifyResource" : "";

  let out = jsDoc(obj.desc);
  out += `export interface ${obj.className}${heritage} {\n`;
  if (isManifest) {
    out += `  readonly schemaVersion: "${version}";\n`;
  }
  for (const prop of obj.properties) {
    const optional = prop.isReq ? "" : "?";
    out += jsDoc(prop.desc, "  ");
    out += `  readonly ${prop.name}${optional}: ${prop.tsType};\n`;
  }
  out += `}\n\n`;
  return out;
}

// The type-state step interfaces: one per required property (each returning the next step), then a
// single Optional step (every optional setter + build) or a bare Build step when there are none.
function emitStepInterfaces(
  obj: ObjectDef,
  requiredProps: PropInfo[],
  optionalProps: PropInfo[],
  definitions: Record<string, SchemaNode>,
): string {
  let out = "";
  for (let i = 0; i < requiredProps.length; i++) {
    const prop = requiredProps[i];
    const stepName = `${obj.className}Builder_${prop.name}`;
    const nextStepName =
      i === requiredProps.length - 1
        ? optionalProps.length > 0
          ? `${obj.className}Builder_Optional`
          : `${obj.className}Builder_Build`
        : `${obj.className}Builder_${requiredProps[i + 1].name}`;

    out += `export interface ${stepName} {\n`;
    out += jsDoc(prop.desc, "  ");
    out += `  ${prop.name}(value: ${prop.tsType}): ${nextStepName};\n`;
    for (const enumVal of getEnumValues(prop.node, definitions)) {
      out += jsDoc(prop.desc, "  ");
      out += `  ${getEnumSetterMethodName(obj.defName, prop.name, enumVal)}(): ${nextStepName};\n`;
    }
    out += `}\n\n`;
  }

  if (optionalProps.length > 0) {
    const optionalStepName = `${obj.className}Builder_Optional`;
    out += `export interface ${optionalStepName} {\n`;
    for (const prop of optionalProps) {
      out += jsDoc(prop.desc, "  ");
      out += `  ${prop.name}(value: ${prop.tsType}): ${optionalStepName};\n`;
      for (const enumVal of getEnumValues(prop.node, definitions)) {
        out += jsDoc(prop.desc, "  ");
        out += `  ${getEnumSetterMethodName(obj.defName, prop.name, enumVal)}(): ${optionalStepName};\n`;
      }
    }
    out += `  build(): ${obj.className};\n`;
    out += `}\n\n`;
  } else {
    out += `export interface ${obj.className}Builder_Build {\n`;
    out += `  build(): ${obj.className};\n`;
    out += `}\n\n`;
  }
  return out;
}

// The builder implementation class: fields, array defaults, primary + enum-helper setters, and the
// runtime required-field guard in build().
function emitImplClass(
  obj: ObjectDef,
  requiredProps: PropInfo[],
  optionalProps: PropInfo[],
  isManifest: boolean,
  version: string,
  definitions: Record<string, SchemaNode>,
): string {
  const builderName = `${obj.className}BuilderImpl`;
  const interfaces = [
    ...requiredProps.map((prop) => `${obj.className}Builder_${prop.name}`),
    optionalProps.length > 0 ? `${obj.className}Builder_Optional` : `${obj.className}Builder_Build`,
  ];

  let out = `class ${builderName} implements ${interfaces.join(", ")} {\n`;
  for (const prop of obj.properties) {
    out += `  private _${prop.name}: any;\n`;
    if (prop.isReq && prop.node.type === "array") {
      out += `  private _${prop.name}Set = false;\n`;
    }
  }
  out += `\n`;

  out += `  constructor() {\n`;
  for (const prop of obj.properties) {
    // Arrays default to an empty list, matching the Java SDK's field initializers.
    if (prop.node.type === "array") {
      out += `    this._${prop.name} = [];\n`;
    }
  }
  out += `  }\n\n`;

  for (const prop of obj.properties) {
    out += `  ${prop.name}(value: ${prop.tsType}): any {\n`;
    out += `    this._${prop.name} = value;\n`;
    if (prop.isReq && prop.node.type === "array") {
      out += `    this._${prop.name}Set = true;\n`;
    }
    out += `    return this;\n`;
    out += `  }\n\n`;
    for (const enumVal of getEnumValues(prop.node, definitions)) {
      out += `  ${getEnumSetterMethodName(obj.defName, prop.name, enumVal)}(): any {\n`;
      out += `    return this.${prop.name}("${enumVal}");\n`;
      out += `  }\n\n`;
    }
  }

  out += `  build(): ${obj.className} {\n`;
  for (const prop of requiredProps) {
    const missingCheck =
      prop.node.type === "array"
        ? `!this._${prop.name}Set || this._${prop.name} === undefined || this._${prop.name} === null`
        : `this._${prop.name} === undefined || this._${prop.name} === null`;
    out += `    if (${missingCheck}) {\n`;
    out += `      throw new Error("Required field '${prop.name}' is missing.");\n`;
    out += `    }\n`;
  }
  out += `    return {\n`;
  if (isManifest) {
    out += `      schemaVersion: "${version}",\n`;
  }
  for (const prop of obj.properties) {
    out += `      ${prop.name}: this._${prop.name},\n`;
  }
  out += `    } as any;\n`;
  out += `  }\n`;
  out += `}\n\n`;
  return out;
}

// The `Model.builder()` namespace entrypoint plus the standalone `ModelBuilder()` function.
function emitEntrypoints(obj: ObjectDef, firstStep: string): string {
  const builderName = `${obj.className}BuilderImpl`;
  let out = `export namespace ${obj.className} {\n`;
  out += `  export function builder(): ${firstStep} {\n`;
  out += `    return new ${builderName}();\n`;
  out += `  }\n`;
  out += `}\n\n`;
  out += `export function ${obj.className}Builder(): ${firstStep} {\n`;
  out += `  return new ${builderName}();\n`;
  out += `}\n\n`;
  return out;
}

function emitObjectBuilder(
  obj: ObjectDef,
  version: string,
  definitions: Record<string, SchemaNode>,
): string {
  const { requiredProps, optionalProps } = splitProps(obj);
  const firstStep = firstStepName(obj, requiredProps, optionalProps);
  return (
    emitStepInterfaces(obj, requiredProps, optionalProps, definitions) +
    emitImplClass(obj, requiredProps, optionalProps, obj.defName === null, version, definitions) +
    emitEntrypoints(obj, firstStep)
  );
}

function generateVersion(schemaPath: string, outDir: string): void {
  const schema: SchemaNode = JSON.parse(fs.readFileSync(schemaPath, "utf-8"));
  const version = schema.version!;
  const definitions = schema.definitions ?? {};
  const objectDefs = collectObjectDefs(schema, definitions);

  let content = `import { ClockifyResource } from "../clockify-resource";\n\n`;
  content += emitEnums(definitions);
  for (const obj of objectDefs) content += emitInterface(obj, version);
  for (const obj of objectDefs) content += emitObjectBuilder(obj, version, definitions);

  const outPath = path.join(outDir, `v${version.replace(".", "_")}.ts`);
  fs.writeFileSync(outPath, content, "utf-8");
  console.log(`Generated manifest builder for version ${version} at ${outPath}`);
}

function argValue(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  if (index === -1) return undefined;
  return process.argv[index + 1];
}

function main() {
  const rootDir = path.join(__dirname, "..");
  const schemasDir = path.resolve(
    argValue("--schemas-dir") ?? path.join(rootDir, "schemas", "clockify-manifests"),
  );
  const outDir = path.resolve(
    argValue("--out-dir") ?? path.join(rootDir, "src", "clockify", "generated"),
  );

  fs.mkdirSync(outDir, { recursive: true });

  const schemas = ["1.2.json", "1.3.json", "1.4.json", "1.5.json"];
  for (const schemaName of schemas) {
    const schemaPath = path.join(schemasDir, schemaName);
    if (fs.existsSync(schemaPath)) {
      generateVersion(schemaPath, outDir);
    } else {
      console.warn(`Schema file not found: ${schemaPath}`);
    }
  }

  const schemaEntries = schemas.map((schemaName) => {
    const version = schemaName.replace(".json", "");
    const schema = JSON.parse(fs.readFileSync(path.join(schemasDir, schemaName), "utf8"));
    return `  ${JSON.stringify(version)}: ${JSON.stringify(schema)},`;
  });
  const schemaContent = [
    "/** Draft-04 Clockify manifest schemas embedded for runtime-neutral validation. */",
    'export type ClockifyEmbeddedManifestSchemas = Readonly<Record<"1.2" | "1.3" | "1.4" | "1.5", object>>;',
    "/** Supported schemas keyed by the manifest's declared schema version. */",
    "export const clockifyManifestSchemas: ClockifyEmbeddedManifestSchemas = {",
    ...schemaEntries,
    "} as const;",
    "",
  ].join("\n");
  fs.writeFileSync(path.join(outDir, "manifest-schemas.ts"), schemaContent, "utf8");
  console.log("Generated generated/manifest-schemas.ts");

  generateManifestValidators(schemasDir, outDir, schemas);

  // Generate index.ts for the generated folder
  let indexContent = "";
  for (const schemaName of schemas) {
    const ver = schemaName.replace(".json", "").replace(".", "_");
    indexContent += `export * as v${ver} from "./v${ver}";\n`;
  }
  indexContent += `export { clockifyManifestSchemas } from "./manifest-schemas";\n`;
  fs.writeFileSync(path.join(outDir, "index.ts"), indexContent, "utf-8");
  console.log(`Generated generated/index.ts`);
}

main();
